### ISSUE TITLE
com.randy420.tools (>=2.2)

### ISSUE THREAD

**Issue by namlee135** [Randy-420/ftt#1]
Hi,

In control file: Depends: mobilesubstrate, com.randy420.tools (>=2.2)
But I search in Bigboss 420 Tools still 2.1

If I change to >=2.1, I can install but I can't export flex.

Where can i find the 2.2?

Thank you.

**Comment by Randy-420** [comment]
https://Randy-420.GitHub.ioOn Sun, Jun 5, 2022 at 4:44 PM Lê Tí ***@***.***> wrote:
Hi,
In control file: Depends: mobilesubstrate, com.randy420.tools (>=2.2)
But I search in Bigboss 420 Tools still 2.1
If I change to >=2.1, I can install but I can't export flex.
Where can i find the 2.2?
Thank you.

**Comment by namlee135** [comment]
Thank you
